name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v3

      - name: Встановлення Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # або інша потрібна версія

      - name: Встановлення залежностей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html flake8-html

      - name: Запуск тестів з pytest і генерація HTML-звіту
        run: |
          pytest --maxfail=1 --disable-warnings --html=reports/test-report.html
        continue-on-error: false

      - name: Запуск перевірки стилю коду з Flake8 і генерація HTML-звіту
        run: |
          flake8 --format=html --htmldir=reports/flake8-report .
        continue-on-error: false

      - name: Архівація звітів
        uses: actions/upload-artifact@v4
        with:
          name: ci-reports
          path: reports/